### PR TITLE
fix minor issues in gen_debug.sh

### PR DESCRIPTION
**Pull request by KireinaHoro**

### CODE REVIEW

**Comment by black-dragon74** [comment]
OS X only uses one date. I will try and implement it in a better way. Update incoming.

**Comment by KireinaHoro** [comment]
Nope, projects such as Gentoo Prefix or Homebrew can introduce GNU
coreutils into the path. (I'm encountering this myself)

2017年12月29日(金) 13:44 Nick <notifications@github.com>:

**Comment by black-dragon74** [comment]
Fixed in Ver 3.0
Regards

**Comment by KireinaHoro** [comment]
Thanks.

**Pull request closed without merging**
